[proxmox]
192.168.X.X ansible_user=Saturday

[openmediavault]
192.168.X.X ansible_user=Saturday ansible_become_password="Sunday"

[homeassistant]
192.168.X.X ansible_user=Saturday ansible_become_password="Sunday"

[monitoring]
192.168.X.X ansible_user=Saturday ansible_become_password="Sunday"

[all:vars]
# Ensure Ansible uses Python 3 on the Debian VMs
ansible_python_interpreter=/usr/bin/python3

# Automatically accept new SSH keys (prevents errors when VMs are destroyed/recreated)
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
